services:
  postgres:
    image: postgres:16
    container_name: portfolio-db-docker
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5433:5432"  
    volumes:
      - postgres_data_final:/var/lib/postgresql/data

volumes:
  postgres_data_final: